site_name: Mozilla Push Service Documentation
repo_url: https://github.com/mozilla-services/push-service
repo_name: Mozilla Push Service
pages:
- Home: 'index.md'
- Design: 'design.md'
- History: 'history.md'
theme: readthedocs
markdown_extensions:
- def_list
